import Product from "./Products";

export const metadata = {
  title: "this is product page",
  description: "Generated by create next app",
};

const ProductPage = () => {
  return (
    <div>
      <Product />
    </div>
  );
};

export default ProductPage;
