import { Geist, Geist_Mono } from "next/font/google";
import "/styles/theme.scss";
import Sidebar from "/components/Sidebar";
import AuthRouter from "/helper/AuthRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthRouter>{children}</AuthRouter>
      </body>
    </html>
  );
}
